### ISSUE TITLE
unauthenticated path access returns error message

### ISSUE THREAD

**Issue by matthewberryman** [usergroupcoop/msf-reach#10]
Should redirect to login page.

```
TypeError: Cannot read property 'split' of undefined
    at Object.fromHeader [as getToken] (/var/app/current/dist/lib/util.js:46:37)
    at middleware (/var/app/current/node_modules/express-jwt/lib/index.js:50:25)
    at Layer.handle [as handle_request] (/var/app/current/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/app/current/node_modules/express/lib/router/index.js:317:13)
    at /var/app/current/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/app/current/node_modules/express/lib/router/index.js:335:12)
    at next (/var/app/current/node_modules/express/lib/router/index.js:275:10)
    at jsonParser (/var/app/current/node_modules/body-parser/lib/types/json.js:103:7)
    at Layer.handle [as handle_request] (/var/app/current/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/app/current/node_modules/express/lib/router/index.js:317:13)
    at /var/app/current/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/app/current/node_modules/express/lib/router/index.js:335:12)
    at next (/var/app/current/node_modules/express/lib/router/index.js:275:10)
    at logger (/var/app/current/node_modules/morgan/index.js:144:5)
    at Layer.handle [as handle_request] (/var/app/current/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/app/current/node_modules/express/lib/router/index.js:317:13)
```

**Comment by talltom** [comment]
Fixed in c49fedafa8abc4923100cfa5ba0fb40b1706d0b1
