### ISSUE TITLE
report card submission throws random errors

### ISSUE THREAD

**Issue by matthewberryman** [usergroupcoop/msf-reach#16]
Sometimes I get an image upload error (initially due to an IAM error, but I resolved that, and now sometimes randomly an image upload error)

Sometimes on submitting a report for an event:
error: Error: Invalid report_key for this event.
    at Connection.parseE (/var/app/current/node_modules/pg/lib/connection.js:567:11)
    at Connection.parseMessage (/var/app/current/node_modules/pg/lib/connection.js:391:17)
    at TLSSocket.<anonymous> (/var/app/current/node_modules/pg/lib/connection.js:129:22)
    at emitOne (events.js:115:13)
    at TLSSocket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:252:12)
    at readableAddChunk (_stream_readable.js:239:11)
    at TLSSocket.Readable.push (_stream_readable.js:197:10)
    at TLSWrap.onread (net.js:589:20)

**Comment by talltom** [comment]
Hi @matthewberryman - I can't recreate this. Is it for a specific event you're seeing this error?

**Comment by matthewberryman** [comment]
Quite possibly was just a browser cache issue—I will take another look later today with a coffee and clean browser at hand. :)

**Comment by matthewberryman** [comment]
I've been unable to recreate on different browser, closing for now.

**Comment by matthewberryman** [comment]
"An error has occurred" on the UI maps onto that bug; the cause I've been able to use to reproduce is #21. Will close this when #21 is closed.

**Comment by matthewberryman** [comment]
Tested with clean database and seems good
